sudo git clone https://github.com/allure-framework/allure1
sudo git clone https://github.com/allure-framework/allure-karma
sudo git clone https://github.com/allure-framework/allure.qatools.ru
sudo git clone https://github.com/allure-framework/allure-pytest
sudo git clone https://github.com/allure-framework/allure-rspec
sudo git clone https://github.com/allure-framework/allure-debian
sudo git clone https://github.com/allure-framework/allure-phpunit
sudo git clone https://github.com/allure-framework/allure-scalatest
sudo git clone https://github.com/allure-framework/allure-teamcity
sudo git clone https://github.com/allure-framework/allure-php-commons
sudo git clone https://github.com/allure-framework/allure-specs
sudo git clone https://github.com/allure-framework/allure-maven
sudo git clone https://github.com/allure-framework/allure-codeception
sudo git clone https://github.com/allure-framework/allure-csharp-commons
sudo git clone https://github.com/allure-framework/allure-nunit2
sudo git clone https://github.com/allure-framework/allure-cucumber
sudo git clone https://github.com/allure-framework/allure-ruby-commons
sudo git clone https://github.com/allure-framework/allure-bamboo
sudo git clone https://github.com/allure-framework/allure-mstest
sudo git clone https://github.com/allure-framework/allure-spock
sudo git clone https://github.com/allure-framework/allure-vstest
sudo git clone https://github.com/allure-framework/allure-cucumberjvm
sudo git clone https://github.com/allure-framework/allure-nose
sudo git clone https://github.com/allure-framework/allure-js-commons
sudo git clone https://github.com/allure-framework/allure-mocha
sudo git clone https://github.com/allure-framework/allure-jasmine
sudo git clone https://github.com/allure-framework/allure-cucumberjs
sudo git clone https://github.com/allure-framework/allure-npm
sudo git clone https://github.com/allure-framework/allure2
sudo git clone https://github.com/allure-framework/allure1-model
sudo git clone https://github.com/allure-framework/allure2-model
sudo git clone https://github.com/allure-framework/allure-behat
sudo git clone https://github.com/allure-framework/allure-python
sudo git clone https://github.com/allure-framework/allure-java
sudo git clone https://github.com/allure-framework/allure-docs
sudo git clone https://github.com/allure-framework/allure-gradle
sudo git clone https://github.com/allure-framework/allure-csharp
sudo git clone https://github.com/allure-framework/allure-idea
sudo git clone https://github.com/allure-framework/allure-demo
sudo git clone https://github.com/allure-framework/allure-vsts
sudo git clone https://github.com/allure-framework/allure-js
sudo git clone https://github.com/allure-framework/allure-ruby
